name: RudderStack Automation Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
      
    env:
      AUTH_USER_EMAIL: ${{ secrets.AUTH_USER_EMAIL }}
      AUTH_USER_PASSWORD: ${{ secrets.AUTH_USER_PASSWORD }}
      MAIL_FROM: ${{ secrets.MAIL_FROM }}
      MAIL_TO: ${{ secrets.MAIL_TO }}

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        #cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - name: Kill any existing Chrome processes
      run: |
          pkill chrome || true
          pkill chromium || true
          rm -rf /tmp/chrome-user-data-* || true
          sleep 2
    - run: npm test
    - name: Upload Cucumber HTML report
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-html-report
        path: ./reports
    - name: Send Email with Cucumber HTML Report
      run: node utils/sendReport.js
